services:
  db:
    image: mysql:8.0
    container_name: eventify-db
    environment:
      MYSQL_ROOT_PASSWORD: Emmanuel123
      MYSQL_DATABASE: eventify
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pEmmanuel123"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: eventify-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/eventify
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Emmanuel123
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
