spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/eventify}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Emmanuel123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.jwt.secret=${JWT_SECRET:pticketing-secret-key-change-in-production-must-be-at-least-256-bits-long-for-hs256}
app.jwt.expiration-ms=86400000

paystack.secret-key=${PAYSTACK_SECRET_KEY:sk_test_eb6db3fb0a8ee7d37be33562b7bf5802ada56e56}
paystack.public-key=${PAYSTACK_PUBLIC_KEY:pk_test_66b63e078f0cefe74a5d278521861f92061b4c4c}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:emmanuelezekwu63@gmail.com}
spring.mail.password=${MAIL_PASSWORD:oyacmkdotyzyctnb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=${FRONTEND_URL:http://localhost:5173}
app.base-url=${BASE_URL:http://localhost:8080/api/v1}
cors.allowed-origins=${FRONTEND_URL:http://localhost:5173}

server.tomcat.max-http-form-post-size=10MB
