package com.example.PTicketing.service;

import com.example.PTicketing.dto.request.CreateExternalOrderRequest;
import com.example.PTicketing.dto.response.ExternalOrderResponse;
import com.example.PTicketing.entity.Event;
import com.example.PTicketing.entity.Order;
import com.example.PTicketing.entity.Ticket;
import com.example.PTicketing.entity.TicketType;
import com.example.PTicketing.enums.EventStatus;
import com.example.PTicketing.enums.PaymentMethod;
import com.example.PTicketing.enums.PaymentStatus;
import com.example.PTicketing.enums.TicketStatus;
import com.example.PTicketing.exception.BadRequestException;
import com.example.PTicketing.exception.DuplicateResourceException;
import com.example.PTicketing.exception.ResourceNotFoundException;
import com.example.PTicketing.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Ticket sales driven by an external channel — currently Brandible's WhatsApp bot.
 *
 * <p>The division of labour: the channel owns the conversation and the Paystack
 * account that collects the money; Eventify owns the event, the inventory, the
 * tickets and the organiser's ledger. A single Paystack reference, generated by
 * the channel and supplied to {@link #createOrder}, is the only shared state.
 *
 * <p>Two properties this has to get right, because money is involved:
 *
 * <ul>
 *   <li><b>Tickets are held at order time, not at payment time.</b> A bank transfer
 *       can take minutes to arrive; without a hold, the buyer can pay for a seat
 *       that sold out while they were typing, leaving us with money and no ticket.
 *   <li><b>Confirmation is idempotent.</b> Paystack retries webhooks and the relay
 *       adds another retry source, so confirmation can arrive twice concurrently.
 *       The transition to PAID is a conditional UPDATE, and only the caller whose
 *       update affected a row mints tickets.
 * </ul>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class IntegrationOrderService {

    private final OrderRepository orderRepository;
    private final EventRepository eventRepository;
    private final TicketTypeRepository ticketTypeRepository;
    private final TicketRepository ticketRepository;
    private final DiscountService discountService;
    private final ReferralService referralService;
    private final PricingService pricingService;
    private final QrHostingService qrHostingService;
    private final TicketDeliveryService ticketDeliveryService;

    /** How long an unpaid external order keeps its seats. */
    @Value("${integration.hold-minutes:30}")
    private int holdMinutes;

    /** How long after an event ends the organiser's share becomes withdrawable. */
    @Value("${integration.payout-hold-hours:24}")
    private int payoutHoldHours;

    @Value("${integration.placeholder-email-domain:tickets.eventify.ng}")
    private String placeholderEmailDomain;

    // ─── Create ──────────────────────────────────────────────────────────────

    @Transactional
    public ExternalOrderResponse createOrder(CreateExternalOrderRequest request) {
        orderRepository.findByPaystackReference(request.getPaystackReference())
                .ifPresent(existing -> {
                    throw new DuplicateResourceException(
                            "An order already exists for reference " + request.getPaystackReference());
                });

        Event event = eventRepository.findById(request.getEventId())
                .orElseThrow(() -> new ResourceNotFoundException("Event not found"));

        if (event.getStatus() != EventStatus.PUBLISHED) {
            throw new BadRequestException("Event is not available for purchase");
        }

        TicketType ticketType = ticketTypeRepository.findById(request.getTicketTypeId())
                .orElseThrow(() -> new ResourceNotFoundException("Ticket type not found"));

        if (!ticketType.getEvent().getId().equals(event.getId())) {
            throw new BadRequestException("Ticket type does not belong to this event");
        }

        if (ticketType.getMaxPerOrder() > 0 && request.getQuantity() > ticketType.getMaxPerOrder()) {
            throw new BadRequestException(
                    "Maximum " + ticketType.getMaxPerOrder() + " tickets per order for this ticket type");
        }

        // Take the seats now. A zero return means someone else got the last ones
        // between the channel quoting a price and this call landing.
        int reserved = ticketTypeRepository.reserveQuantity(ticketType.getId(), request.getQuantity());
        if (reserved == 0) {
            int available = ticketType.getQuantity() - ticketType.getTicketsSold();
            throw new BadRequestException(available <= 0
                    ? "This ticket type is sold out"
                    : "Not enough tickets available. Only " + available + " left");
        }

        BigDecimal subtotal = ticketType.getPrice().multiply(BigDecimal.valueOf(request.getQuantity()));
        BigDecimal discountAmount = BigDecimal.ZERO;

        if (request.getDiscountCode() != null && !request.getDiscountCode().isBlank()) {
            discountService.validateAndApply(request.getDiscountCode(), event.getId());
            discountAmount = discountService.calculateDiscount(
                    request.getDiscountCode(), event.getId(), subtotal);
        }

        BigDecimal afterDiscount = subtotal.subtract(discountAmount);
        BigDecimal feeAmount = pricingService.calculateFee(event.getType(), afterDiscount, request.getQuantity());
        BigDecimal totalAmount = afterDiscount.add(feeAmount);

        Order order = Order.builder()
                .orderRef("PTK-" + UUID.randomUUID().toString().substring(0, 12).toUpperCase())
                .event(event)
                .subtotal(ticketType.isFree() ? BigDecimal.ZERO : subtotal)
                .feeAmount(feeAmount)
                .discountAmount(discountAmount)
                .totalAmount(totalAmount)
                .paymentMethod(PaymentMethod.PAYSTACK)
                .paymentStatus(PaymentStatus.PENDING)
                .currency("NGN")
                .paystackReference(request.getPaystackReference())
                .buyerPhone(request.getBuyerPhone())
                .buyerName(request.getBuyerName())
                .buyerEmail(resolveEmail(request))
                .discountCode(request.getDiscountCode())
                .referralCode(request.getReferralCode())
                .ticketTypeId(ticketType.getId())
                .quantity(request.getQuantity())
                .sourceChannel(request.getSourceChannel())
                .holdExpiresAt(LocalDateTime.now().plusMinutes(holdMinutes))
                // Stamped now rather than derived when the balance is read, so a
                // later edit to the event date cannot move money that has already
                // been released.
                .releasableAt(event.getEndDate() != null
                        ? event.getEndDate().plusHours(payoutHoldHours) : null)
                .build();

        order = orderRepository.save(order);

        log.info("External order {} created for event {} ({} × {}), holding until {}",
                order.getOrderRef(), event.getId(), request.getQuantity(),
                ticketType.getName(), order.getHoldExpiresAt());

        return toResponse(order, event, ticketType, null, false);
    }

    // ─── Confirm ─────────────────────────────────────────────────────────────

    /**
     * Marks a paid order as such and mints its tickets.
     *
     * <p>Safe to call repeatedly with the same reference: subsequent calls return
     * the tickets already issued with {@code newlyIssued = false}.
     */
    @Transactional
    public ExternalOrderResponse confirmPayment(String paystackReference) {
        // Claim BEFORE loading anything. claimPaid is a bulk update that clears the
        // persistence context, so an Order read beforehand would be left detached
        // with a stale status and its lazy event association would fail on access.
        // The database decides who mints: exactly one concurrent caller sees 1 here.
        int claimed = orderRepository.claimPaid(paystackReference, LocalDateTime.now());

        Order order = orderRepository.findByPaystackReference(paystackReference)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "No order for reference " + paystackReference));

        Event event = order.getEvent();
        TicketType ticketType = order.getTicketTypeId() != null
                ? ticketTypeRepository.findById(order.getTicketTypeId()).orElse(null)
                : null;

        if (claimed == 0) {
            List<Ticket> existing = ticketRepository.findByOrderId(order.getId());
            log.info("Confirmation for {} is a repeat — returning {} existing ticket(s)",
                    paystackReference, existing.size());

            ExternalOrderResponse repeat = toResponse(order, event, ticketType, existing, false);

            // Deliver even though we did not mint. Another path may have won the
            // claim and had no way to deliver — the web /orders/verify endpoint
            // confirms orders but knows nothing about message channels, and a buyer
            // returning from Paystack hits it before the webhook lands. Without this,
            // whoever loses the race silently drops delivery and the buyer is left
            // holding a paid order with no ticket in their chat.
            //
            // Safe to repeat: send-ticket-whatsapp claims the session before
            // messaging and returns already_delivered on a second attempt.
            if (order.getPaymentStatus() == PaymentStatus.PAID && !existing.isEmpty()) {
                ticketDeliveryService.deliverAsync(repeat, order.getBuyerPhone(), order.getSourceChannel());
            }

            return repeat;
        }

        // The hold has been converted into a sale; it must not be swept later.
        order.setHoldExpiresAt(null);
        order = orderRepository.save(order);

        if (order.getDiscountCode() != null) {
            discountService.incrementUsage(order.getDiscountCode());
        }
        if (order.getReferralCode() != null) {
            referralService.trackSale(order.getReferralCode());
        }

        int quantity = order.getQuantity() != null ? order.getQuantity() : 1;
        List<Ticket> tickets = new ArrayList<>();

        for (int i = 0; i < quantity; i++) {
            String qrText = UUID.randomUUID().toString();
            Ticket ticket = ticketRepository.save(Ticket.builder()
                    .ticketType(ticketType)
                    .order(order)
                    .event(event)
                    .buyerEmail(order.getBuyerEmail())
                    .buyerName(order.getBuyerName())
                    .qrCode(qrText)
                    // Uploaded once, here, and stored. Retried confirmations reuse it.
                    .qrImageUrl(qrHostingService.publish(qrText, "ticket-" + qrText))
                    .status(TicketStatus.ACTIVE)
                    .build());
            tickets.add(ticket);
        }

        // Stock was already decremented at order time — deliberately not repeated here.

        ExternalOrderResponse response = toResponse(order, event, ticketType, tickets, true);

        log.info("Order {} confirmed, {} ticket(s) issued for event {}",
                order.getOrderRef(), tickets.size(), event.getId());

        // Hand off to the channel that sold it. Async and best-effort — a delivery
        // failure must not roll back a completed sale.
        ticketDeliveryService.deliverAsync(response, order.getBuyerPhone(), order.getSourceChannel());

        return response;
    }

    /**
     * Re-sends an already-confirmed order to the channel that sold it.
     *
     * <p>Exists because confirmation and delivery can happen on different paths: the
     * web {@code /orders/verify} endpoint confirms an order but knows nothing about
     * message channels, and a buyer returning from Paystack usually reaches it before
     * the webhook does. Whoever loses that race would otherwise drop delivery.
     *
     * <p>Best-effort by design — never throws, because the caller has already taken
     * the buyer's money and issued their tickets. Repeat calls are safe:
     * send-ticket-whatsapp claims the session before messaging.
     */
    @Transactional(readOnly = true)
    public void deliverExistingOrder(String paystackReference) {
        try {
            Order order = orderRepository.findByPaystackReference(paystackReference).orElse(null);
            if (order == null || order.getPaymentStatus() != PaymentStatus.PAID) return;
            if (order.getBuyerPhone() == null || order.getBuyerPhone().isBlank()) return;

            List<Ticket> tickets = ticketRepository.findByOrderId(order.getId());
            if (tickets.isEmpty()) return;

            TicketType ticketType = order.getTicketTypeId() != null
                    ? ticketTypeRepository.findById(order.getTicketTypeId()).orElse(null)
                    : null;

            ExternalOrderResponse response =
                    toResponse(order, order.getEvent(), ticketType, tickets, false);

            ticketDeliveryService.deliverAsync(response, order.getBuyerPhone(), order.getSourceChannel());

        } catch (Exception e) {
            log.error("Delivery retry failed for {} — tickets are valid and retrievable: {}",
                    paystackReference, e.getMessage());
        }
    }

    // ─── Lookup ──────────────────────────────────────────────────────────────

    // Deliberately not readOnly: resolveQrImageUrl may backfill a missing QR image,
    // and a read-only transaction sets flush mode to MANUAL, so that write would be
    // silently dropped rather than persisted.
    @Transactional
    public ExternalOrderResponse getByReference(String paystackReference) {
        Order order = orderRepository.findByPaystackReference(paystackReference)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "No order for reference " + paystackReference));

        TicketType ticketType = order.getTicketTypeId() != null
                ? ticketTypeRepository.findById(order.getTicketTypeId()).orElse(null)
                : null;

        List<Ticket> tickets = order.getPaymentStatus() == PaymentStatus.PAID
                ? ticketRepository.findByOrderId(order.getId())
                : null;

        return toResponse(order, order.getEvent(), ticketType, tickets, false);
    }

    // ─── Hold expiry ─────────────────────────────────────────────────────────

    /**
     * Returns seats from orders that were never paid for.
     *
     * <p>Covers every channel, not just this one: the web checkout also reserves at
     * order time, so an abandoned card attempt leaves a hold here too. Without
     * this, abandoned checkouts would permanently consume inventory and an event
     * would appear sold out while seats remained.
     *
     * <p>Only PENDING orders are swept. PENDING_VERIFICATION (manual bank transfer)
     * keeps its hold deliberately, since a human still has to confirm it — those
     * need clearing by an admin rather than a timer.
     */
    @Scheduled(fixedRateString = "${integration.hold-sweep-ms:300000}")
    @Transactional
    public void releaseExpiredHolds() {
        List<Order> expired = orderRepository.findAll().stream()
                .filter(o -> o.getPaymentStatus() == PaymentStatus.PENDING)
                .filter(o -> o.getHoldExpiresAt() != null)
                .filter(o -> o.getHoldExpiresAt().isBefore(LocalDateTime.now()))
                .toList();

        for (Order order : expired) {
            if (order.getTicketTypeId() != null && order.getQuantity() != null) {
                ticketTypeRepository.releaseQuantity(order.getTicketTypeId(), order.getQuantity());
            }
            order.setPaymentStatus(PaymentStatus.FAILED);
            order.setHoldExpiresAt(null);
            orderRepository.save(order);

            log.info("Released expired hold on order {} ({} ticket(s))",
                    order.getOrderRef(), order.getQuantity());
        }

        if (!expired.isEmpty()) {
            log.info("Swept {} expired ticket hold(s)", expired.size());
        }
    }

    // ─── Mapping ─────────────────────────────────────────────────────────────

    private String resolveEmail(CreateExternalOrderRequest request) {
        if (request.getBuyerEmail() != null && !request.getBuyerEmail().isBlank()) {
            return request.getBuyerEmail();
        }
        // Confirmation emails and buyer lookups both key on email, so every order
        // needs one. Derived from the phone when the channel has no real address.
        String digits = request.getBuyerPhone().replaceAll("\\D", "");
        return digits + "@" + placeholderEmailDomain;
    }

    /**
     * Returns the ticket's stored QR image, uploading it only if it is missing.
     *
     * <p>The upload happens at mint time. This exists for the tickets that missed
     * it — an upload that failed while Cloudinary was misconfigured, or tickets
     * issued by the web checkout, which has no need for a hosted image. Those
     * backfill on first request and are then persisted like any other.
     */
    private String resolveQrImageUrl(Ticket ticket) {
        if (ticket.getQrImageUrl() != null && !ticket.getQrImageUrl().isBlank()) {
            return ticket.getQrImageUrl();
        }

        String url = qrHostingService.publish(ticket.getQrCode(), "ticket-" + ticket.getQrCode());
        if (url != null) {
            ticket.setQrImageUrl(url);
            ticketRepository.save(ticket);
        }
        return url;
    }

    private ExternalOrderResponse toResponse(Order order,
                                             Event event,
                                             TicketType ticketType,
                                             List<Ticket> tickets,
                                             boolean newlyIssued) {

        List<ExternalOrderResponse.IssuedTicket> issued = null;
        if (tickets != null) {
            issued = tickets.stream()
                    .map(t -> ExternalOrderResponse.IssuedTicket.builder()
                            .ticketId(t.getId())
                            .qrCode(t.getQrCode())
                            .qrImageUrl(resolveQrImageUrl(t))
                            .ticketTypeName(ticketType != null ? ticketType.getName() : null)
                            .build())
                    .toList();
        }

        LocalDateTime releasableAt = event.getEndDate() != null
                ? event.getEndDate().plusHours(payoutHoldHours)
                : null;

        return ExternalOrderResponse.builder()
                .orderRef(order.getOrderRef())
                .paystackReference(order.getPaystackReference())
                .paymentStatus(order.getPaymentStatus())
                .eventId(event.getId())
                .eventTitle(event.getTitle())
                .eventSlug(event.getSlug())
                .eventVenue(event.getVenue())
                .eventStartDate(event.getStartDate())
                .eventEndDate(event.getEndDate())
                .organizerId(event.getOrganizer() != null ? event.getOrganizer().getId() : null)
                .ticketTypeName(ticketType != null ? ticketType.getName() : null)
                .quantity(order.getQuantity() != null ? order.getQuantity() : 0)
                .subtotal(order.getSubtotal())
                .feeAmount(order.getFeeAmount())
                .discountAmount(order.getDiscountAmount())
                .totalAmount(order.getTotalAmount())
                .currency(order.getCurrency())
                .releasableAt(releasableAt)
                .tickets(issued)
                .newlyIssued(newlyIssued)
                .build();
    }
}
